const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.LOS,
		C3.Plugins.gamepad,
		C3.Behaviors.scrollto,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Acts.SetFullscreenQuality,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.gamepad.Cnds.CompareAxis,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsEffectEnabled,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Exps.Y
	];
};
self.C3_JsPropNameTable = [
	{botao: 0},
	{Sine: 0},
	{Tween: 0},
	{BOTOES: 0},
	{Sine2: 0},
	{dwight_arte_menu: 0},
	{titulo: 0},
	{Sprite5: 0},
	{Caixa: 0},
	{cursor: 0},
	{personagem: 0},
	{TXT_Dialogo: 0},
	{TXT_Nome: 0},
	{fundoCenas: 0},
	{cena: 0},
	{quadro: 0},
	{Text: 0},
	{Sprite3: 0},
	{Sprite2: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{transição: 0},
	{Audio: 0},
	{Solid: 0},
	{Solido_TileMap: 0},
	{estado_animação: 0},
	{Platform: 0},
	{LineOfSight: 0},
	{Player: 0},
	{Gamepad: 0},
	{Qual_Pista: 0},
	{interagido: 0},
	{Pistas_objetos: 0},
	{TileMap_Estrutura: 0},
	{Objetos_sem_interaçao: 0},
	{objetos_fundo: 0},
	{sombra: 0},
	{lampada: 0},
	{zona: 0},
	{ScrollTo: 0},
	{camera: 0},
	{comodo: 0},
	{porta: 0},
	{sangue: 0},
	{colisor: 0},
	{Dialogo_tocando: 0},
	{Dialogo_escolha: 0},
	{PassivelDeDialogo: 0},
	{Dialogo_ordem: 0},
	{cozinha_dialogos: 0},
	{sala_dialogos: 0},
	{Dialogo_assunto: 0},
	{cozinha_explorada: 0},
	{sala_explorada: 0},
	{Qual_dialogo: 0},
	{clicou: 0},
	{botão: 0},
	{numero_pg: 0},
	{numero: 0},
	{local: 0}
];

self.InstanceType = {
	BOTOES: class extends self.ISpriteInstance {},
	dwight_arte_menu: class extends self.ISpriteInstance {},
	titulo: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Caixa: class extends self.ISpriteInstance {},
	cursor: class extends self.ISpriteInstance {},
	personagem: class extends self.ISpriteInstance {},
	TXT_Dialogo: class extends self.ITextInstance {},
	TXT_Nome: class extends self.ITextInstance {},
	fundoCenas: class extends self.ISpriteInstance {},
	quadro: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	transição: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Solido_TileMap: class extends self.ITilemapInstance {},
	Player: class extends self.ISpriteInstance {},
	Gamepad: class extends self.IInstance {},
	Pistas_objetos: class extends self.ISpriteInstance {},
	TileMap_Estrutura: class extends self.ITilemapInstance {},
	Objetos_sem_interaçao: class extends self.ISpriteInstance {},
	objetos_fundo: class extends self.ISpriteInstance {},
	sombra: class extends self.ISpriteInstance {},
	lampada: class extends self.ISpriteInstance {},
	zona: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	porta: class extends self.ISpriteInstance {},
	sangue: class extends self.ISpriteInstance {},
	colisor: class extends self.ISpriteInstance {}
}